name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    strategy:
      matrix:
        runner:
          - os: ubuntu-latest
            name: Linux
            deploy-snapshots: true
          - os: windows-latest
            name: Windows
            deploy-snapshots: false
          - os: macos-latest
            name: MacOS
            deploy-snapshots: false
    name: Build (${{ matrix.runner.name }})
    if: ${{ github.repository == 'spring-io/initializr' }}
    runs-on: ${{ matrix.runner.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'

      - name: Maven verify
        if: ${{ !matrix.runner.deploy-snapshots }}
        run: ./mvnw --no-transfer-progress --batch-mode --update-snapshots verify

      - name: Maven deploy
        if: ${{ matrix.runner.deploy-snapshots }}
        run: echo "Would deploy"

      - name: Send notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          run-name: ${{ format('{0} | {1}', github.ref_name, matrix.runner.name) }}
